spring:
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672                        # 是客户端的地址，不是浏览器管理端的                 #
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  http:
    encoding:
      charset: utf-8
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.producer        #所有Entity别名类所在包
  mapper-locations: com/producer/mapping/*.xml

logging:
  level:
    tk:
      mybatis: trace
server:
  port: 8080
